name: Update Reasons Weekly

on:
  schedule:
    # Runs every Monday at 3 AM UTC
    - cron: '0 3 * * 1'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  update-reasons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Call update-reasons function
        run: |
          curl -X GET https://awmzvzjyyrreunvfntlw.supabase.co/functions/v1/slack-no-update-reasons

      - name: Update README and commit
        run: |
          DATE=$(date +'%B %d, %Y')
          sed -i "s|\*\*Last reasons update:\*\* .*|**Last reasons update:** $DATE|" README.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "reasons were checked and updated. Last update date is $DATE"
            git push origin main
          fi
